services:
  gameapi-soap:
    build: .
    container_name: gameapi-soap
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://gameapi-mysql:3306/si_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: gameapi
      SPRING_DATASOURCE_PASSWORD: gameapi
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    networks:
      - gameapi-net

volumes:
  mysql_data:

networks:
  gameapi-net:
    external: true
