services:
  mysql:
    build: .
    container_name: gameapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: si_db
      MYSQL_USER: gameapi
      MYSQL_PASSWORD: gameapi
    networks:
      - gameapi-net
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  gameapi-net:
    external: true