services:
  mysql:
    build: .
    container_name: si-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: si_db
      MYSQL_USER: user
      MYSQL_PASSWORD: PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gameapi-net

volumes:
  mysql_data:

networks:
  gameapi-net:
    external: true